[build]
  publish = "dist"
  functions = "src/netlify/functions"

[[redirects]]
  from = "/airtable/*"
  to = "/.netlify/functions/airtable"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
