[build]
  publish = "dist"
  edge_functions = "src/netlify/edge-functions"

[[edge_functions]]
  function = "airtable"
  path = "/airtable/*"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
